services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: postgres
    networks:
      - dev_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  loeysingsregister:
    image: ${DOCKER_REGISTRY}/testlab2-loeysingsregister:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8080"
    networks:
      - dev_network
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres?currentSchema=testlab2_loeysingsregister'
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Passw0rd

  kravregister:
    image: ${DOCKER_REGISTRY}/testlab2-krav:latest
    ports:
      - "8002:8080"
    networks:
      - dev_network
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres?currentSchema=testlab2_krav'
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Passw0rd

  testing:
    image: ${DOCKER_REGISTRY}/testlab2-testing:latest
    ports:
      - "8001:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev_network
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres?currentSchema=testlab2_testing'
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Passw0rd
      LOEYSINGSREGISTER_HOST: loeysingsregister
      KRAVREGISTER_HOST: kravregister

  frontend:
    image: ${DOCKER_REGISTRY}/testlab2-frontend:latest
    ports:
      - "8080:8080"
    networks:
      - dev_network
    depends_on:
      - testing


networks:
  dev_network: