name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Set up node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: install frontend dependencies
        working-directory: frontend
        run: npm ci
      - name: build frontend app
        working-directory: frontend
        run: npm run build
      - name: compile and test server app
        run: mvn -B test
      - name: make public folder
        run: mkdir -p target/classes/public
      - name: copy frontend app
        run: cp -R frontend/dist/* target/classes/public/
      - name: build and push image
        run: mvn -B compile jib:build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ca-ddt-testlab2-test-frontend -g RG-DDT-Testlab --image acrddtprod.azurecr.io/testlab2-frontend:${{ github.sha }} --subscription ${{ secrets.SUBSCRIPTION_ID }}
