name: Java CI

on: [ push ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"
          cache: maven
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: install frontend dependencies
        working-directory: frontend
        run: npm ci
      - name: build frontend app
        working-directory: frontend
        run: npm run build
      - name: Setup github packages
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.GH_USER }}",
                "password": "${{ secrets.PAT }}"
            }]
      - name: test frontend app
        working-directory: frontend
        run: npm run test:ci
      - name: compile and test server app
        run: mvn -B test
      - name: make public folder
        run: mkdir -p target/classes/public
      - name: copy frontend app
        run: cp -R frontend/dist/* target/classes/public/
      - name: build and push image
        run: mvn -B compile jib:build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true

      - name: Azure CLI Action
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ca-ddt-testlab2-test-frontend -g RG-DDT-Testlab --image acrddtprod.azurecr.io/testlab2-frontend:${{ github.sha }} --subscription ${{ secrets.SUBSCRIPTION_ID }}

# Kommentert ut til man har funnet løsning på innlogging før tester

#  acceptance_tests:
#    needs: deploy
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: lts/*
#      - name: Install dependencies
#        working-directory: frontend
#        run: npm ci
#      - name: Install Playwright Browsers
#        working-directory: frontend
#        run: npx playwright install --with-deps chromium
#      - name: Run Playwright tests
#        working-directory: frontend
#        run: npx playwright test
#      - uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: playwright-report
#          path: frontend/playwright-report/
#          retention-days: 30
